version: '3'

services:

  web:
    hostname: web
    image: httpd
    ports:
      - "80:80"
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: httpd.access
        fluentd-async: 'true'
    networks:
      - efk

  fluentd:
    hostname: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:8.13.4
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=changeme"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - efk

  kibana:
    hostname: kibana
    image: kibana:8.13.4
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - efk

networks:
  efk:
    driver: bridge