version: '3'

services:

  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access
        fluentd-async: 'true'

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:8.13.4
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_PASSWORD=changeme"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.13.4
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"